### PR TITLE
Add archlinux arm to rate-mirrors 

### PR DESCRIPTION
**Pull request by Rippanda12**

### CODE REVIEW

**Comment by Rippanda12** [comment]
ignore the mirrorlist it pulls the mirrorlist straight from archlinuxarms github
https://raw.githubusercontent.com/archlinuxarm/PKGBUILDs/master/core/pacman-mirrorlist/mirrorlist

**Comment by Rippanda12** [comment]
i think it should work now? not sure please test

**Comment by westandskif** [comment]
thank you, I should be able to look into this tomorrow.

_> i think it should work now? not sure please test_
have you tried to run it yourself? :)

**Comment by Rippanda12** [comment]
it works i think but not sure i have no experience coding in rust it sorts mirrors but idk if it does correctly

**Comment by Rippanda12** [comment]
works

**Comment by westandskif** [comment]
As agreed above, I'm looking into this tomorrow. Is there a reliable way to fetch urls & **countries**? I see them as comments in the [file](https://raw.githubusercontent.com/archlinuxarm/PKGBUILDs/master/core/pacman-mirrorlist/mirrorlist), but not sure if we can rely on it.

P.S. of course countries matter when there's a lot of mirrors and this isn't the case yet.

**Comment by Rippanda12** [comment]
honestly no idea for now it uncomments each link and tests invididually i dont have the required knowledge to do more complex hopping

**Comment by Rippanda12** [comment]
https://archlinuxarm.org/about/mirrors

**Comment by westandskif** [comment]
No-no, I haven't meant this. This was just a question about whether Archlinux ARM has an API endpoint like arch does: see "JSON format" link [here](https://archlinux.org/mirrors/status/)

**Comment by Rippanda12** [comment]
no they dont

**Comment by Rippanda12** [comment]
the only reason im making this mod is cus the default mirror sucks (the geoip distributive one)

**Comment by westandskif** [comment]
Got it, thank you! I believe, tomorrow I'm checking this on my end, merging and releasing to AUR.

**Comment by westandskif** [comment]
thank you! have a great day too! :)

**Comment by westandskif** [comment]
Managed to do it today - [v0.11.0](https://github.com/westandskif/rate-mirrors/releases/tag/v0.11.0).
Also pushed to AUR.

**Pull request merged**
