### PR TITLE
feat: add chaotic-aur

### PR DESCRIPTION
**Pull request by teppyboy**
I used archarm as a base then edited it to make it work with chaotic-aur mirrors.

### CODE REVIEW

**Comment by westandskif** [comment]
Thank you! Merging.
I'm going to update README and release new versions today.

**Comment by westandskif** [comment]
Done: both on [AUR](https://aur.archlinux.org/packages?K=westandskif&SeB=m)

**Comment by teppyboy** [comment]
thanks

**Comment by teppyboy** [comment]
@westandskif I added `archlinuxcn` too in [my fork](https://github.com/teppyboy/rate-mirrors/tree/archlinuxcn), should I create a new PR?

**Comment by westandskif** [comment]
@teppyboy yes, please, create a new one! I'll do my best to accept and release in the evening

**Pull request merged**
